### ISSUE TITLE
entry.value must not be null in SuccessObject

### ISSUE THREAD

**Issue by carlosmuvi** [Skyost/Bonsoir#17]
First of all, thanks for the lib! 

**Describe the bug**

I'm getting this crash when discovering devices. 
 
```
E/AndroidRuntime( 6015): Process: XXX, PID: 6015
E/AndroidRuntime( 6015): java.lang.IllegalStateException: entry.value must not be null
E/AndroidRuntime( 6015): 	at fr.skyost.bonsoir.SuccessObject.getAttributes(SuccessObject.kt:62)
E/AndroidRuntime( 6015): 	at fr.skyost.bonsoir.SuccessObject.serviceToJson(SuccessObject.kt:44)
E/AndroidRuntime( 6015): 	at fr.skyost.bonsoir.SuccessObject.toJson(SuccessObject.kt:25)
E/AndroidRuntime( 6015): 	at fr.skyost.bonsoir.discovery.BonsoirDiscoveryListener$onServiceResolved$1.run(BonsoirDiscoveryListener.kt:138)
E/AndroidRuntime( 6015): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 6015): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 6015): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 6015): 	at android.app.ActivityThread.main(ActivityThread.java:7660)
E/AndroidRuntime( 6015): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6015): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 6015): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

I'm seeing devices being discovered in the logs, so it seems to be a parsing issue with one of those specific devices.

**To Reproduce**

Just started exploring devices on my network, not sure if it'd be reproducible in others.

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 11

Using Flutter and [cast](https://github.com/jonathantribouharet/flutter_cast) on top of Bonsoir.

**Comment by natebgurutech** [comment]
Same error here, here's a little more verbose log from my Android device:

```
[+1582 ms] D/bonsoir (18948): [23680] Bonsoir discovery started : _googlecast._tcp
[  +69 ms] D/bonsoir (18948): [23680] Bonsoir has found a service : name: Chromecast-972af924bbbf07f2c431b37dafedbfc4, type: _googlecast._tcp., host: null, port: 0, txtRecord: 
[  +16 ms] D/bonsoir (18948): [23680] Bonsoir has resolved a service : name: Chromecast-972af924bbbf07f2c431b37dafedbfc4, type: ._googlecast._tcp, host: /10.22.2.101, port: 8009, txtRecord: bs=FA8FCA51A5A5  ca=200709#cd=73EEDE6F0F9FF8F964AA37CE5C9F3015
                                                                                                                                                                                                                                                            fn=Office
TVic=/setup/icon.png#id=972af924bbbf07f2c431b37dafedbfc4
[   +8 ms] D/AndroidRuntime(18948): Shutting down VM
[        ] E/AndroidRuntime(18948): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(18948): Process: com.wilma.wilma, PID: 18948
[        ] E/AndroidRuntime(18948): java.lang.IllegalStateException: entry.value must not be null
[        ] E/AndroidRuntime(18948):     at fr.skyost.bonsoir.SuccessObject.getAttributes(SuccessObject.kt:62)
[        ] E/AndroidRuntime(18948):     at fr.skyost.bonsoir.SuccessObject.serviceToJson(SuccessObject.kt:44)
[        ] E/AndroidRuntime(18948):     at fr.skyost.bonsoir.SuccessObject.toJson(SuccessObject.kt:25)
[        ] E/AndroidRuntime(18948):     at fr.skyost.bonsoir.discovery.BonsoirDiscoveryListener$onServiceResolved$1.run(BonsoirDiscoveryListener.kt:138)
[        ] E/AndroidRuntime(18948):     at android.os.Handler.handleCallback(Handler.java:883)
[        ] E/AndroidRuntime(18948):     at android.os.Handler.dispatchMessage(Handler.java:100)
[        ] E/AndroidRuntime(18948):     at android.os.Looper.loop(Looper.java:241)
[        ] E/AndroidRuntime(18948):     at android.app.ActivityThread.main(ActivityThread.java:7617)
[        ] E/AndroidRuntime(18948):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(18948):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[        ] E/AndroidRuntime(18948):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
[  +17 ms] I/Process (18948): Sending signal. PID: 18948 SIG: 9
[  +35 ms] Service protocol connection closed.
[        ] Lost connection to device.
```

**Comment by oandreyev** [comment]
The same error with Pixel3/Android 11 and Mi  TV Stick

**Comment by Skyost** [comment]
Should be fixed _now_ with the merging of #19.

**Comment by vanlooverenkoen** [comment]
When will there be a new version be released to pub.dev

**Comment by Skyost** [comment]
@vanlooverenkoen I'm currently in hollidays. When I'll come back, I'll need to fix some other problems, and I'll upload the release.

**Comment by vanlooverenkoen** [comment]
Alright perfect.

I did a dependency_overrides and everything is working fine for my flutter [flutter_case_ui](https://github.com/vanlooverenkoen/flutter_cast_ui/tree/feature/cast-ui) plugin.

I want to wait for the stable release before I publish to pub.dev.

 Enjoy your holliday :D

**Comment by Skyost** [comment]
That's okay but you can always try the master branch to see if it fits your needs in its current state 😉

```dart
dependencies:
  bonsoir:
    git:
      url: git://github.com/Skyost/Bonsoir.git
      path: bonsoir
```

**Comment by vanlooverenkoen** [comment]
Yes that is exactly what I am doing :D
