### ISSUE TITLE
java.lang.IllegalArgumentException: listener not registered

### ISSUE THREAD

**Issue by epireyn** [Skyost/Bonsoir#3]
### Describe the bug
I tried to run my app (which uses broadcast) but I got this issue: 
```[34897] Bonsoir service registration failed : name: Werewolves, type: werewolves_online_broadcast, host: null, port: 6665, txtRecord: , error code : 0
E/AndroidRuntime(16031): FATAL EXCEPTION: NsdManager
E/AndroidRuntime(16031): Process: be.epireyn.werewolf, PID: 16031
E/AndroidRuntime(16031): java.lang.IllegalArgumentException: listener not registered
E/AndroidRuntime(16031): 	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:50)
E/AndroidRuntime(16031): 	at android.net.nsd.NsdManager.getListenerKey(NsdManager.java:467)
E/AndroidRuntime(16031): 	at android.net.nsd.NsdManager.unregisterService(NsdManager.java:541)
E/AndroidRuntime(16031): 	at fr.skyost.bonsoir.broadcast.BonsoirRegistrationListener.dispose(BonsoirRegistrationListener.kt:90)
E/AndroidRuntime(16031): 	at fr.skyost.bonsoir.broadcast.BonsoirRegistrationListener.dispose$default(BonsoirRegistrationListener.kt:88)
E/AndroidRuntime(16031): 	at fr.skyost.bonsoir.broadcast.BonsoirRegistrationListener.onRegistrationFailed(BonsoirRegistrationListener.kt:66)
E/AndroidRuntime(16031): 	at android.net.nsd.NsdManager$ServiceHandler.handleMessage(NsdManager.java:405)
E/AndroidRuntime(16031): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(16031): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(16031): 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

### To Reproduce
Run this code on Android: 
```Dart
void _toggleBroadcast({bool kill = false}) async {
    if (_broadcast == null && !kill) {
      _broadcast = BonsoirBroadcast(
          service: BonsoirService(
              name: 'Werewolves', type: BROADCAST_TYPE, port: 6665));
      await _broadcast.ready;
      await _broadcast.start();
    } else {
      if (_broadcast != null) await _broadcast.stop();
      _broadcast = null;
    }
  }
```

### Expected behavior
To be able to send broadcast messages without crashes

### Desktop (please complete the following information):
Windows 10

### Smartphone (please complete the following information):
HMD Global Nokia 7 plus

**Comment by akash6190** [comment]
Try checking the value for `BROADCAST_TYPE` according to  https://stackoverflow.com/a/37160509 the value for type should be `_some-service._tcp`.

**Comment by Skyost** [comment]
@epireyn Would it be possible for you to give me your `BROADCAST_TYPE` ? (@akash6190 is right, it should be in a very specific format)

**Comment by epireyn** [comment]
Hello!
Akash were right, I fixed the issue now.

Thank you!
