### ISSUE TITLE
java.util.ConcurrentModificationException is throwed by BonsoirServiceDiscovery.kt

### ISSUE THREAD

**Issue by heiha100** [Skyost/Bonsoir#93]
**Describe the bug**
```Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, null, null, java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1029)
	at java.util.ArrayList$Itr.next(ArrayList.java:982)
	at g5.b.z(BonsoirServiceDiscovery.kt:13)
	at g5.b.F(BonsoirServiceDiscovery.kt:11)
	at e5.i.onMethodCall(MethodCallHandler.kt:514)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:18)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:19)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:42)
	at io.flutter.embedding.engine.dart.DartMessenger.a(Unknown Source:0)
	at io.flutter.embedding.engine.dart.a.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:1013)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:328)
	at android.app.ActivityThread.main(ActivityThread.java:9176)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:651)
       at MethodChannel._invokeMethod(platform_channel.dart:334)
```

**To Reproduce**
Not sure how to reproduce. But i guess it caused by restarting BonsoirDiscovery

**Smartphone (please complete the following information):**
 - Device: 型号：IQOO Neo9
 - OS: Android 14

**Additional context**
I try restart BonsoirDiscovery and BonsoirBroadcast when the app back to foreground or network connectivity changed.

**Comment by heiha100** [comment]
> Your stacktrace seems obfuscated, can you please provide a non-obfuscated stacktrace ?
I updated the stacktrace
